import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul className={`list-disc pl-6`}>
        <li>
          <Link href="/rest/landingGetQueryKeyUserApi">/rest/landingGetQueryKeyUserApi</Link>
        </li>
        <li>
          <Link href="/rest/clickGetQueryKeyUserApi">/rest/clickGetQueryKeyUserApi</Link>
        </li>
        <li>
          <Link href="/rest/clickGetQueryKeyTodoApi">/rest/clickGetQueryKeyTodoApi</Link>
        </li>
        <li>
          <Link href="/rest/clickGetQueryKeyTaskApi">/rest/clickGetQueryKeyTaskApi</Link>
        </li>
        <li>
          <Link href="/rest/landingGetQueryKeyTasksApi">/rest/landingGetQueryKeyTasksApi</Link>
        </li>
        <li>
          <Link href="/rest/clickMutationTaskApi">/rest/clickMutationTaskApi</Link>
        </li>
        <li>
          <Link href="/graphQL/landingQueryUsersApi">/graphQL/useQueryUsersApi</Link>
        </li>
      </ul>
    </div>
  )
}

export default Home
