import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`p-4`}>
        <ul className={`list-disc pl-6`}>
          <li className={`py-1`}>
            <Link href="/rest/landingGetQueryKeyUserApi">/rest/landingGetQueryKeyUserApi</Link>
          </li>
          <li className={`py-1`}>
            <Link href="/rest/clickGetQueryKeyUserApi">/rest/clickGetQueryKeyUserApi</Link>
          </li>
          <li className={`py-1`}>
            <Link href="/rest/clickGetQueryKeyTodoApi">/rest/clickGetQueryKeyTodoApi</Link>
          </li>
          <li className={`py-1`}>
            <Link href="/rest/clickGetQueryKeyTaskApi">/rest/clickGetQueryKeyTaskApi</Link>
          </li>
          <li className={`py-1`}>
            <Link href="/rest/landingGetQueryKeyTasksApi">/rest/landingGetQueryKeyTasksApi</Link>
          </li>
          <li className={`py-1`}>
            <Link href="/rest/clickMutationTaskApi">/rest/clickMutationTaskApi</Link>
          </li>
          <li className={`py-1`}>
            <Link href="/graphQL/landingGetUsersApi">/graphQL/landingGetUsersApi</Link>
          </li>
          <li className={`py-1`}>
            <Link href="/graphQL/clickGetUserApi">/graphQL/clickGetUserApi</Link>
          </li>
          <li className={`py-1`}>
            <Link href="/graphQL/clickMutationUserApi">/graphQL/clickMutationUserApi</Link>
          </li>
        </ul>
      </div>
    </div>
  )
}

export default Home
